### ISSUE TITLE
Support for Request Headers?

### ISSUE THREAD

**Issue by ojw** [imalsogreg/servant-reflex#20]
There's a `HasClient` instance for `(Header sym a :> sublayout)`, but it doesn't actually set the header.  I played around trying to get it to work, but have failed so far - I can't figure out how to actually use the `Behavior t (Either String a)` to produce a `Client t m sublayout`.  Is there a clear direction to getting headers to work?  If the type looked like

```
  type Client t m (Header sym a :> sublayout) =
    Either String a -> Client t m sublayout
```

instead of

```
  type Client t m (Header sym a :> sublayout) =
    Behavior t (Either String a) -> Client t m sublayout
```

if would be reasonably easy to set the header value, but that doesn't typecheck.

Clearly I'm a bit out of my depth here :/.

Is there a clear path forward to actually set headers?  I'd be happy to do some grunt work and submit a PR, but am failing so far.

**Comment by ojw** [comment]
Ack, never mind, it's pretty simple:

```
instance (KnownSymbol sym, ToHttpApiData a,
          HasClient t m sublayout, MonadWidget t m)
      => HasClient t m (Header sym a :> sublayout) where

  type Client t m (Header sym a :> sublayout) =
    Behavior t (Either String a) -> Client t m sublayout

  clientWithRoute Proxy q req baseurl eitherVal =
    clientWithRoute (Proxy :: Proxy sublayout)
                    q
                    (Servant.Common.Req.addHeader hname eitherVal req)
                    baseurl

    where hname = symbolVal (Proxy :: Proxy sym)
```

seems to work.

I'll create a PR, but could of course be missing something obvious.

**Comment by ojw** [comment]
Ah, but that sets the header value of `Right "foo"` to `"right foo"` rather than `"foo"`.  I'll take a look at `addHeader`...

**Comment by ojw** [comment]
If I hack `addHeader` to look like

```
addHeader :: (ToHttpApiData a, Reflex t) => String -> Behavior t (Either String a) -> Req t -> Req t
addHeader name val req = req { headers = headers req
  ++ [(name, fmap (unpack . either (\e -> "") (\s -> toHeader s)) val)]
```, then the header values look like I would expect for `Right headerVal`s.  It doesn't handle the `Left` case well, because I'm not really sure what the `Left` case represents.

Does this seem like a reasonable direction?

**Comment by imalsogreg** [comment]
Thanks for the PR! So, the type for header arguments is `Behavior t (Either String a)` because we want the XHRRequest to be a function of the header value over all time. But there may be times when there is no valid value for the header, for example, if a user input that needs validation is being used to computer the header value. What can exist at all times is an `Either String a` where `Left` means "no valid value".

Right now there is some very fishy code here: https://github.com/imalsogreg/servant-reflex/blob/master/src/Servant/Common/Req.hs#L146-L152  Instead of failing the whole request during the processing of headers, it drops invalid headers on a case by case basis... then it ignores the headers list altogether. Can you try to replicate the pattern going on for query parameters and captures, where a single invalid parameter prevents the request from being built?

**Comment by ojw** [comment]
Definitely, I'll take a look when I get home. Thanks for the explanation!

**Comment by ojw** [comment]
Took another stab that I hope is more in the direction you're looking for.  It could still use some work - in particular, `xhrHeaders` is now pretty messy.
