### ISSUE TITLE
Cannot calling Api inside HTML widget

### ISSUE THREAD

**Issue by Rizary** [imalsogreg/servant-reflex#90]
I got some error when calling the api inside some widget. Here is the code: 

https://github.com/Rizary/hackage-matrix-builder/blob/v3-tags/src-ui.v3/src/Main.hs#L465

but when I call the api outside the widget by only change 
`evTagPkg <- fmapMaybe reqSuccess <$> getV2PackageTags (constDyn $ Right pn) evPB`

 into 

`evTagPkg <- fmapMaybe reqSuccess <$> getV2PackageTags (constDyn $ Right "ace") evPB` 

and place the code above or below 
`https://github.com/Rizary/hackage-matrix-builder/blob/v3-tags/src-ui.v3/src/Main.hs#L273`

It work fine.

here is the error:
```
Couldn't match type ‘Event t1 (ReqResult () (Vector TagN))’
                     with ‘ReqResult tag0 b0’
      Expected type: Event t () -> m (f0 (ReqResult tag0 b0))
        Actual type: Client
                       t1 f0 (Capture "" PkgN :> Get '[JSON] (Vector TagN)) ()
    • The function ‘getV2PackageTags’ is applied to two arguments,
      but its type ‘ClientFuns t1 f0
                    -> Client t1 f0 (Capture "" PkgN :> Get '[JSON] (Vector TagN)) ()’
      has only one
      In the second argument of ‘(<$>)’, namely
```

The question is can we call the api inside the widget generation? like when creating the HTML element (e.g. `ol`, `li`) like the above example.

**Comment by benkolera** [comment]
The shadowing that you are doing with the record wildcards is tripping you up. 

If you see https://github.com/Rizary/hackage-matrix-builder/blob/v3-tags/src-ui.v3/src/Main.hs#L371 you'll see a bit that is making the client and then exporting every extracted record field (the real client function) into that scope. 

At line 465, you don't have such a thing in scope, so you are actually getting the record accessor (see that the type of the function is from ClientFuns -> Client) from API. If you drop in the same thing as line 371 into the where block on the broken function I'd imagine that it'd work. 


As a personal suggestion, I personally prefer expanding out the type family evaluations in my client type so that the callers of the client get much more friendly error messages. That way you map it to the haskell function once and everything else deals with normal haskell errors rather than having to unravel type families when they call a thing incorrectly. It's a bit more boilerplate, but you write the client once and then use it lots so I think that amortises well enough. See https://github.com/qfpl/reflex-realworld-example/blob/master/frontend/src/Frontend/Conduit/Client/Internal.hs#L105 . @imalsogreg what do you recommend? Feel free to override this advice! :slightly_smiling_face:

**Comment by Rizary** [comment]
@benkolera thank you.. I barely notice that. Regarding your suggestion, I need to discuss with @hvr first.

**Comment by imalsogreg** [comment]
Thanks a lot for the diagnosis, @benkolera! I usually do what you do - write type annotations for client functions in non-servant terms. Between servant and reflex, there are a lot of ways to get mixed up about types, so declaring the endpoints' types is a great sanity check.

**Comment by Rizary** [comment]
Thanks, I will close this issue and move to the matrix repo regarding type annotations.
